openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /:
    get:
      tags:
      - command-controller
      operationId: execCommand
      parameters:
      - name: command
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
      - command-controller
      operationId: execCommandPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Command'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /thread:
    get:
      tags:
      - command-controller
      operationId: execCommandThread
      parameters:
      - name: command
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /sanity:
    get:
      tags:
      - command-controller
      operationId: execCommandSanity
      parameters:
      - name: command
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /pb:
    get:
      tags:
      - command-controller
      operationId: execCommandPB
      parameters:
      - name: command
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Command:
      type: object
      properties:
        value:
          type: string
