version: "3"

services:
  orientdb:
    image: orientdb
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
    volumes:
      - orientdb_vol:/orientdb/databases


volumes:
  orientdb_vol:
